name: 'KidDog&co'
favicon: null
layout_spectrum: 0.50214
typography_spectrum: 0.11092
title: 'KidDog&co'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d49d69'
    - '#76c05a'
    - '#3c3c3c'
  brandStrength: 0.6668788525275886
  lightness: 0.625
  saturation: 0.8674177718348801
  rhythmicContrast: 0.5
purpose: []
