analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d49d69'
    - '#76c05a'
    - '#3c3c3c'
  brandStrength: 0.4375
  lightness: 0.655405
  rhythmicContrast: 0.5
  saturation: 0.867417
cta: {}
layout_spectrum: 0.652027
name: 'KidDog&co'
opengraph: {}
purpose: []
typography_spectrum: 0.099662
